services:
  wordpress-develop:
    depends_on:
      - php
      - blackfire

  php:
    image: spacedmonkey/php-blackfire:${LOCAL_PHP-latest}
    environment:
      - PHP_BLACKFIRE=1
      - BLACKFIRE_CLIENT_ID=${BLACKFIRE_CLIENT_ID-}
      - BLACKFIRE_CLIENT_TOKEN=${BLACKFIRE_CLIENT_TOKEN-}

  blackfire:
    image: blackfire/blackfire:2
    networks:
      - wpdevnet
    ports: ["8307"]
    environment:
      BLACKFIRE_LOG_LEVEL: 4
      BLACKFIRE_SERVER_ID: $BLACKFIRE_SERVER_ID
      BLACKFIRE_SERVER_TOKEN: $BLACKFIRE_SERVER_TOKEN
      BLACKFIRE_CLIENT_ID: $BLACKFIRE_CLIENT_ID
      BLACKFIRE_CLIENT_TOKEN: $BLACKFIRE_CLIENT_TOKEN
