name: Code Linting

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/lint.yml'
      - '**.js'
      - '**.json'
      - '**.mjs'
      - '.eslint*'
      - '.nvmrc'
      - '**/package.json'
      - 'package-lock.json'
  pull_request:
    branches:
      - main
      - 'feature/**'
    paths:
      - '.github/workflows/lint.yml'
      - '**.js'
      - '**.json'
      - '**.mjs'
      - '.eslint*'
      - '.nvmrc'
      - '**/package.json'
      - 'package-lock.json'
    types:
      - opened
      - reopened
      - synchronize

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: styfle/cancel-workflow-action@0.12.1
      - uses: actions/checkout@v4
      - name: Setup Node.js (via .nvmrc)
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - name: npm install
        run: npm ci
      - name: Lint
        run: npm run lint
